# Generated by Django 3.2.16 on 2022-11-30 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='cae',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='nif',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='seller',
            name='region',
            field=models.CharField(choices=[('Regiao Norte', 'Regiao Norte'), ('Regiao Centro', 'Regiao Centro'), ('Regiao Sul', 'Regiao Sul'), ('Açores', 'Açores'), ('Madeira', 'Madeira')], default='Regiao Norte', max_length=13),
        ),
        migrations.AddField(
            model_name='seller',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
