# Generated by Django 3.2.16 on 2022-12-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221130_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='user',
        ),
        migrations.AddField(
            model_name='tourist',
            name='address',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='tourist',
            name='tourist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(default='nothing'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cae',
            field=models.CharField(default='nothing', max_length=5),
        ),
        migrations.AlterField(
            model_name='seller',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='nif',
            field=models.CharField(default='nothing', max_length=9),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(default='nothing', max_length=9),
        ),
        migrations.AlterField(
            model_name='seller',
            name='website',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='phone',
            field=models.CharField(default='nothing', max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tourist',
            field=models.BooleanField(default=False),
        ),
    ]
