# Generated by Django 3.2.16 on 2022-12-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221212_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='company',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
